# Generated by Django 3.2.5 on 2023-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linkedindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputlink', models.URLField(max_length=255)),
                ('outputcsv', models.TextField(blank=True)),
            ],
        ),
    ]
